### ISSUE TITLE
Validation job using art/larg4

### ISSUE THREAD

**Issue by brettviren** [WireCell/wire-cell-gen#11]
Not an issue with WCT per se but one "customer" of WCT sim is to use it in art/larsoft with LArG4 supplying the depos.  In principle, if LArG4 acts as advertised then it does not need explicit testing as the larwirecell integration code has its own supposedly equivalent producer of depos.  However, to guard against unexpected differences or against LArG4 depos tickling bugs in WCT we should validate with this chain either for or just after 0.8.0 is released.

**Comment by brettviren** [comment]
Some things to validate on WCT side
- [ ] Understand what geometry update was done recently in microboone
- [ ] Check that drift velocity needs change or not.
- [ ] Check global time offset 
- [ ] Check misconfigured channels are correct and consistent between both signal + noise sim.
- [ ] Check that configured dead channels are correctly removed by NF in simulation job
- [ ] Compare a frame made from an `ISimChannel` to full sim drift frame

**Comment by jyotiphy** [comment]
We will also need to add capability of skipping NF for simulation job.

**Comment by lastgeorge** [comment]
I do not think that we can skip NF for simulation job if we simulate i) RCRC response, ii) misconfigured channels.  

In addition, I think the current plan is to add dead channel through NF module in simulation.

**Comment by brettviren** [comment]
Validation done by Hanyu.
