### ISSUE TITLE
Noise models and noise source

### ISSUE THREAD

**Issue by brettviren** [WireCell/wire-cell-gen#3]
The upper layer partly ready:

  https://github.com/WireCell/wire-cell-gen/blob/master/src/NoiseSource.cxx

What needs to change is to fill in the empty `waveform()` method and do so
following the pattern like we do for the recombination models.

Ie, define an `INoiseModel` with a single method.  This method takes a
channel ID number and returns a frequency-space amplitude distribution
(maybe by const reference to facilitate caching inside the model
object).  The binning of the distribution is also needed by that can be
a configuration item.

`NoiseSource` then needs to `lookup()` a `INoiseModel` by type/name, call it
on each channel and perform proper sampling and statistics.

**Comment by lastgeorge** [comment]
In order to do the noise simulation properly, we will need the following functions:
    1. for each channel, get its wire length, or capacitance. For MicroBooNE, we already have a simple function to describe this.
    2. for each channel, we need to know its corresponding gain and shaping time setting. Given these, we need to access the corresponding electronics response in frequency domain.
    3. We need a Gaussian random number generator.
    4. We need to access FFT and iFFT ( I guess this is available now).
    5. We can make a special MicroBooNE function, the input would be wire length, gain, shaping time, and frequency, and return the mean amplitude.
   
    Let's talk about this a little bit next week. I can implement this easily with the input from Jyoti and the infrastructure.

**Comment by brettviren** [comment]
1. Total wire length is provided via an `IAnodePlane` object.  The `INoiseModel` would be configured with the type/name of this object and `lookup()` and hold on to an instance.
2. is not well represented currently.  There is just the single electronics response.  I'll work on this.  Probably it goes into `IAnodePlane` which is turning into a kitchen sink.
3. for now, use C++'s `std` random services.  
4. yes, `dft()` and `idft()` are in the `util` package
5. what about this has to be special to MB?  Certainly the input parameters and data but does anything in the code need to be special?

**Comment by brettviren** [comment]
Related issue: https://github.com/WireCell/wire-cell-iface/issues/2

**Comment by brettviren** [comment]
This was done a while ago.  See EmpericalNoiseModel class.
